name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Build
        run: npm install && npm run build
        env:
          REACT_APP_API_KEY = ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN = ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID = ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_DATABASE_URL = ${{ secrets.REACT_APP_DATABASE_URL }}
          REACT_APP_STORAGE_BUCKET = ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID = ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID = ${{ secrets.REACT_APP_APP_ID }}
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
